{% set name = "ecvl-cpu" %}
{% set version = "v1.0.0" %}
{% set sha256 = "55f42273851d648b09ed5c29ecad3cd57b79b2ab7f3d641d35d65ac6b1f8c429" %}

package:
  name: {{ name|lower }}
  version: {{ version[1:] }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/ecvl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cpu ==1.0.3b
    - python {{ py_ver }}
    - libnsl
  run:
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cpu ==1.0.3b
    - python {{ py_ver }}


about:
  home: https://github.com/deephealthproject/ecvl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: European Computer Vision Library
