{% set name = "ecvl-cpu" %}
{% set version = "v1.0.3" %}
{% set sha256 = "66f0b4306f5e1831cd26976a6fa1f240c721a6fa2238ee9e6c3ee1e2d4fbfde5" %}

package:
  name: {{ name|lower }}
  version: {{ version[1:] }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/ecvl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cpu ==1.1b
    - python {{ py_ver }}
    - libnsl
  run:
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cpu ==1.1b
    - python {{ py_ver }}


about:
  home: https://github.com/deephealthproject/ecvl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: European Computer Vision Library
