{% set name = "ecvl-cpu" %}
{% set version = "v0.3.5" %}
{% set sha256 = "7c3d6e687c78ff1592af0c83dbb1da0ac71827d2518c0104ebd75a743f10d367" %}

package:
  name: {{ name|lower }}
  version: {{ version[1:] }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/ecvl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cpu ==1.0.2a0
    - python {{ py_ver }}
  run:
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cpu ==1.0.2a0
    - python {{ py_ver }}


about:
  home: https://github.com/deephealthproject/ecvl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: European Computer Vision Library
