FROM nvidia/cuda:10.1-cudnn8-runtime

ENV PATH="/opt/conda/bin:${PATH}"

RUN apt-get -y update && apt-get -y install wget && \
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /opt/conda && \
    conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

RUN conda create -y -n test && \
    conda install -y -n test -c conda-forge -c dhealth eddl-cudnn && \
    conda init bash
