FROM conda-gpu-base

COPY ecvl /ecvl

RUN conda config --add channels dhealth && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict && \
    conda build ecvl
