FROM conda-gpu-base

COPY pyecvl /pyecvl

RUN conda config --add channels dhealth && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict && \
    conda build pyecvl
