FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

# dhealth/linux-64 must contain the ecvl-cpu conda package
COPY dhealth /dhealth

RUN conda index /dhealth/ && \
    conda create -y -n ecvl-test && \
    conda config --append channels file://dhealth && \
    conda config --append channels conda-forge && \
    conda install -y -n ecvl-test ecvl-cpu

COPY test_ecvl.sh /test.sh
