FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

COPY ecvl /ecvl

RUN conda config --append channels conda-forge && \
    conda build ecvl
