FROM conda-cpu-base

COPY pyeddl /pyeddl

RUN conda config --add channels dhealth && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict && \
    conda build pyeddl
