FROM continuumio/miniconda3

RUN conda update -y conda && \
    conda install -y conda-build && \
    conda update -y conda-build

COPY ecvl /ecvl

RUN conda config --add channels dhealth && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict && \
    conda build ecvl
