{% set name = "eddl-cpu" %}
{% set version = "v1.0.2a" %}
{% set sha256 = "70d6067d44cb547e218236e5bb72faf45f602a7b8214f869626ca47f241481a0" %}

package:
  name: {{ name|lower }}
  version: {{ version[1:] }}0

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - eigen >=3.3.7,<3.3.8
    - zlib 1.2*
    - protobuf 3.11*
  run:
    - {{ pin_compatible('eigen', max_pin='x.x') }}
    - {{ pin_compatible('zlib', max_pin='x.x') }}
    - {{ pin_compatible('protobuf', max_pin='x.x') }}
    - wget

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: European Distributed Deep Learning Library
