{% set name = "eddl-cpu" %}
{% set version = "v0.5.4a" %}
{% set sha256 = "50acb25976f14e6caf5535b82fc760dd1a0f7e0b81db83906b62eddd8eba0db7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - cmake
    - {{ compiler('cxx') }}
  host:
    - eigen
    - zlib
    - protobuf 3.11
  run:
    - eigen
    - zlib
    - {{ pin_compatible('protobuf', max_pin='x.x') }}
    - graphviz
    - wget

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  summary: European Distributed Deep Learning Library
