{% set name = "pyecvl-cpu" %}
{% set version = "0.11.0" %}
{% set sha256 = "3871b4d7fad30e301a5c256fbe5d03ebd5f541fca56b4b90b8af2d358f625ec9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/pyecvl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - ecvl-cpu ==0.4.0a
    - eddl-cpu ==1.0.2a0
    - numpy
    - pip
    - pybind11 <2.6
    - python {{ py_ver }}
    - setuptools
  run:
    - ecvl-cpu ==0.4.0a
    - pyeddl-cpu ==1.0.0
    - numpy
    - python {{ py_ver }}

about:
  home: https://github.com/deephealthproject/pyecvl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for the ECVL library
