{% set name = "pyecvl-cpu" %}
{% set version = "1.2.0" %}
{% set sha256 = "d6dfc6376a65bf5d661c1f9f53bf37e2ce6f8b615b0baf2f9d092f6a23e4b73c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/pyecvl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - ecvl-cpu ==1.0.2
    - eddl-cpu ==1.1b
    - numpy
    - pip
    - pybind11 <2.6
    - python {{ py_ver }}
    - setuptools
  run:
    - ecvl-cpu ==1.0.2
    - pyeddl-cpu ==1.3.0
    - numpy
    - python {{ py_ver }}

about:
  home: https://github.com/deephealthproject/pyecvl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for the ECVL library
