{% set name = "pyeddl-gpu" %}
{% set version = "1.3.1" %}
{% set sha256 = "97d1f263320ba3522904a29650ca9cfdb247510583a7ca4a8bc5312c7415405d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/pyeddl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cudatoolkit ==11.3.1
    - eddl-gpu ==1.1b
    - eigen >=3.3.7,<3.3.8
    - numpy
    - pip
    - pybind11 <2.6
    - python {{ py_ver }}
    - setuptools
  run:
    - cudatoolkit ==11.3.1
    - eddl-gpu ==1.1b
    - numpy
    - python {{ py_ver }}

about:
  home: https://github.com/deephealthproject/pyeddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for the EDDL library
