{% set name = "eddl-gpu" %}
{% set version = "0.7.1" %}
{% set sha256 = "d454dd71b9045ab3cf9b98e415fe871757b3c72eba24bfe6cfe574d5c078e85c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - cmake <3.18
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cudatoolkit-dev 10.1*
    - eigen >=3.3.7,<3.3.8
    - zlib 1.2*
    - protobuf 3.11*
  run:
    - cudatoolkit >=10.1,<10.2a0
    - {{ pin_compatible('eigen', max_pin='x.x') }}
    - {{ pin_compatible('zlib', max_pin='x.x') }}
    - {{ pin_compatible('protobuf', max_pin='x.x') }}
    - wget

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: European Distributed Deep Learning Library
