{% set name = "eddl-gpu" %}
{% set version = "0.6.0" %}
{% set sha256 = "a13aba429d2ea110fba66d4f756b59aff1f32480ad260f08db8baa0d40ae25be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cudatoolkit-dev 10.1*
    - eigen >=3.3.7
    - zlib 1.2*
    - protobuf 3.11*
  run:
    - cudatoolkit >=10.1,<10.2a0
    - {{ pin_compatible('eigen', max_pin='x.x') }}
    - {{ pin_compatible('zlib', max_pin='x.x') }}
    - {{ pin_compatible('protobuf', max_pin='x.x') }}
    - wget

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: European Distributed Deep Learning Library
