{% set name = "ecvl-cudnn" %}
{% set version = "v1.0.2" %}
{% set sha256 = "6e76e946ab43c4f293a059a471b40ac3099ccf13f0b2b4626ef906dd0ee713d8" %}

package:
  name: {{ name|lower }}
  version: {{ version[1:] }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/deephealthproject/ecvl/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - make
    - cmake >=3.17.2
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cudatoolkit-dev ==11.3.1
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cudnn ==1.1b
    - python {{ py_ver }}
    - libnsl
  run:
    - cudatoolkit ==11.3.1
    - py-opencv <4
    - yaml-cpp ==0.6.3
    - openslide ==3.4.1
    - dcmtk ==3.6.5
    - eddl-cudnn ==1.1b
    - python {{ py_ver }}


about:
  home: https://github.com/deephealthproject/ecvl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: European Computer Vision Library
